services:
  
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - postgres:/var/lib/postgres/data
      - ./services/infra/postgres:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - ./services/infra/pgadmin/server.json:/pgadmin4/servers.json

volumes:
  postgres: