services:

  ui:
    build:
      context: ./services/mankkoo-ui
      dockerfile: Dockerfile
    container_name: mankkoo-ui
    depends_on:
      - core
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  core:
    build:
      context: ./services/mankkoo
      dockerfile: Dockerfile
    container_name: mankkoo-core
    environment:
      - ENV=prod
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["flask", "run"]
  
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - postgres:/var/lib/postgres/data
      - ./services/infra/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - ./services/infra/pgadmin/server.json:/pgadmin4/servers.json

volumes:
  postgres: